### ISSUE TITLE
[Wish] hxiclam -- for windower!

### ISSUE THREAD

**Issue by farchord** [jimmy58663/hxiclam#3]
This is a suggestion, and not a bug.

I play on FFXI/Horizon from a Linux computer, and to avoid memory leaks (Long story, not gonna elaborate here for everyone's sanity) I switched to using the Windower.

At this point, most things work fine. I even fixed pet ability IDs to work with skillchains (Windower's version of chains). One thing I'm lacking though is a windower version of hxiclam.

It would be really awesome if the addon was converted over to windower. I won't hold my breath though, I get what I am asking :) Heck, if I get time I might just try to take hand at it myself.

**Comment by jimmy58663** [comment]
Initial release in [v1.2.2](https://github.com/jimmy58663/hxiclam/releases/tag/v1.2.2).

- There is no GUI for the settings.
- There is no font sizing specifically for the Bucket Weight

If you know of a Windower addon that does either of the above let me know and I can take a look through their code.
